# Generated by Django 3.2.16 on 2024-03-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20240303_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
    ]
